language: python
python:
 - 2.7
 - 3.4
 - 3.5
 - 3.6
 - 3.7

before_install:
 - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
 - sudo dpkg -i erlang-solutions_1.0_all.deb
 - sudo apt-get -qq update
 - sudo apt-get install -y esl-erlang=1:19.3.6 rabbitmq-server

install:
 - pip install .
 - pip install -r requirements.txt

script:
 - nosetests --with-coverage tests

after_success:
 - coverage combine
 - coveralls