language: python
python:
 - 3.4
 - 3.5
 - 3.6

services:
 - rabbitmq

install:
 - pip install .
 - pip install -r requirements.txt

script:
 - nosetests --with-coverage tests

after_success:
 - coverage combine
 - coveralls