language: python
python:
 - 2.7
 - 3.2
 - 3.3
 - 3.4
 - 3.5
 - 3.6
 - 3.7

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y rabbitmq-server

install:
 - pip install .
 - pip install -r requirements.txt

script:
 - nosetests --with-coverage tests

after_success:
 - coverage combine
 - coveralls