language: python
python:
 - 2.7
 - 3.4
 - 3.5
 - 3.6
 - 3.7

before_install:
 - wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.3/rabbitmq-server_3.7.3-1_all.deb
 - wget http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_20.2.2-1~debian~jessie_amd64.deb
 - sudo dpkg -i esl-erlang_20.2.2-1~debian~jessie_amd64.deb
 - sudo dpkg -i rabbitmq-server_3.7.3-1_all.deb

install:
 - pip install .
 - pip install -r requirements.txt

script:
 - nosetests --with-coverage tests

after_success:
 - coverage combine
 - coveralls